import { BookStatus } from 'enums/book-status.enum';
import type { Book } from '@Models/index';

const currentDate = new Date('2022');

export const HomeBooks: Book[] = [
  {
    id: '1',
    title: 'The Brothers Karamazov',
    author: 'Dostoievsky',
    status: BookStatus.COMPLETED,
    rating: 80,
    pages: 0,
    username: 'user1',
    image: undefined,
    review: undefined,
    read_pages: [],
    createdAt: String(currentDate),
    updatedAt: String(currentDate),
  },
  {
    id: '2',
    title: 'Steppenwolf',
    author: 'Hesse',
    status: BookStatus.READING,
    rating: 40,
    pages: 20,
    username: 'user2',
    image: undefined,
    review: undefined,
    read_pages: [],
    createdAt: String(currentDate),
    updatedAt: String(currentDate),
  },
  {
    id: '3',
    title: 'One hundred years of solitude',
    author: 'Márquez',
    status: BookStatus.READY,
    rating: 20,
    pages: 417,
    username: 'user3',
    image: undefined,
    review: undefined,
    read_pages: [],
    createdAt: String(currentDate),
    updatedAt: String(currentDate),
  },
  {
    id: '4',
    title: 'The Symposium',
    author: 'Plato',
    status: BookStatus.TO_READ,
    rating: 0,
    pages: 111,
    username: 'user4',
    image: undefined,
    review: undefined,
    read_pages: [],
    createdAt: String(currentDate),
    updatedAt: String(currentDate),
  },
];
