export enum UIState {
  SIGN_IN = 'SIGN_IN',
  LOGGED = 'LOGGED',
  SIGN_UP = 'SIGN_UP',
  CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUBMIT = 'FORGOT_PASSWORD_SUBMIT',
}
